version: '3.9'

services:
  backend:
    image: firelace386/computex:backend
    build: ./Computex
    ports:
      - "8000:8000"

  frontend:
    image: firelace386/computex:frontend
    build: ./ComputexFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=recipe
    volumes:
      - ddata:/var/lib/postgresql/data

volumes:
  ddata:
